name: Docker Build and Push

concurrency: docker-publish

on:
  schedule:
    - cron: '23 4 */7 * *'
  push:
    branches: [ main ]
    tags:
      - 'v*'
    paths-ignore:
     - README.md
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        dockerfile: [ubuntu24]
        include:
          - dockerfile: ubuntu24
            tags: |
              latest
              ubuntu24
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Determine tags
        id: tags
        run: |
          TAGS="${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME }}:${{ matrix.dockerfile }}"
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
            TAGS="$TAGS,${{ env.IMAGE_NAME }}:${VERSION_TAG}"
          fi
          echo "tags=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          tags: ${{ steps.tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
